# Generated by Django 5.0.6 on 2026-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(db_index=True, max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True)),
                ('area', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('contact_phone', models.CharField(max_length=50)),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
                'indexes': [models.Index(fields=['contact_phone', 'city', 'property_type'], name='listings_dedup_idx')],
            },
        ),
    ]
