# Generated by Django 5.0.6 on 2026-06-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_dedup_idx',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['contact_phone', 'city', 'property_type', 'area'], name='listings_dedup_idx'),
        ),
    ]
